### PR TITLE
Extensive `#[func]` testing (GDScript -> Rust calls)

### PR DESCRIPTION
**Pull request by Bromeon**
Generates both ptrcall and varcall tests now.
Adds several values to the test input.

Currently fails in some ptrcall cases; possibly related to #138 and #195.

### CODE REVIEW

**Comment by Bromeon** [comment]
bors try

**Comment by Bromeon** [comment]
bors try

**Comment by sayaks** [comment]
seems some of these issue are also related to #195

**Comment by Bromeon** [comment]
Merged as part of #204.

**Pull request closed without merging**
