### PR TITLE
Enable experimental wasm support

### PR DESCRIPTION
**Pull request by zecozephyr**
Instead of messing around with godot export templates or emscripten in order to either:

 1. dlopen the gdextension lib with global flag (which may come with unforeseen problems from broadly exposing miscellaneous new symbols from the dso).

 2. Reconsider the lookup scope of `dynCall_<sig>` in the generated `invoke_<sig>` methods (i.e. when an invoke_<sig> is generated, also make it it remember the originating dso and fall back to lookup in the dso exports if the `dynCall` is not found globally)

I instead opt to simply promote the selected troublesome symbols from the dso to Module scope as early as possible at the gdextension entry point, whilst also searching for and executing the constructor methods which set up state for the subsequent class registrations.

-----------

Tested With:
    Godot Engine v4.1.3.stable.official [f06b6836a]
	(default export templates, dlink variant)
    rustc 1.75.0-nightly (2f1bd0729 2023-10-27)
    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.47 (431685f05c67f0424c11473cc16798b9587bb536)
    Chrome Version 120.0.6093.0 (Official Build) canary (arm64)

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-493

**Review by PgBiel — COMMENTED** [review]
This is looking awesome :rocket: :crab: !!! Months of efforts from multiple contributors seem to have paid out :smile: 

Thank you very much @zecozephyr for the brilliant patch. Also thanks to everyone else involved, including @Esption for the recent 32-bit improvements and general help over at the WASM Discord thread, @Bromeon for all the support throughout, and the Godot contributors for all the recent work allowing GDExtension to work on WASM. :+1:

**Comment by Bromeon** [comment]
Thanks a lot for this fantastic pull request, this is a great step towards WebAssembly support! ❤️ 

For future reference, I tested this PR as follows:
1. Download emscripten
    - check out https://emscripten.org/docs/getting_started/downloads.html
    - clone https://github.com/emscripten-core/emsdk
2. Install emscripten
    - `emsdk install latest`
    - `emsdk activate latest`
       (not using `--persistent` as that might mess up env vars)
    - add directory with `emcc` manually to `PATH`
3. Compile Rust for WASM _and for Desktop_ (to open editor)
    - the `build-wasm.sh` script in this PR does this
4. Open Godot editor in `dodge-the-creeps/godot`
    - Godot 4.1.3-stable
5. Set up web export
    - in Project > Export
    - Enable _Extensions Support_ option
6. Launch game in browser
    - either from Godot grafik icon
    - or via URL `http://localhost:8060/tmp_js_export.html`

For me (Windows 10) it runs on Edge, **but not on Firefox** at the moment.

That's probably something we or Godot devs need to investigate in the future. For GDScript itself, Firefox definitely works (I recently released [a LD54 game](https://ldjam.com/events/ludum-dare/54/stardust-slingshot/) for Web). Either way, I'm super happy the Dodge-the-Creeps example already works with WASM ☺️

**Comment by Bromeon** [comment]
Regarding Firefox not working (freezing during load), see also https://github.com/godotengine/godot-cpp/pull/1247#issuecomment-1742197814.

**Pull request merged**
