### PR TITLE
Use instance_id_or_none in DynamicRefCount to fix #172

### LINKED ISSUE #172: Destructor for `Gd<Object>` panics on `instance_id()`
The current `Mem` implementation for `Object` uses the infallible version of `instance_id` for inc and dec operations, which leads to spurious `instance_id` panics in some cases when the underlying Object isn't ref-counted.

Currently, `DynamicRefCount` is defined:

```rust
    impl Memory for DynamicRefCount {
        fn maybe_init_ref<T: GodotClass>(obj: &Gd<T>) {
            out!("  Dyn::init  <{}>", std::any::type_name::<T>());
            if obj.instance_id().is_ref_counted() {
                StaticRefCount::maybe_init_ref(obj);
            }
        }

        fn maybe_inc_ref<T: GodotClass>(obj: &Gd<T>) {
            out!("  Dyn::inc   <{}>", std::any::type_name::<T>());
            if obj.instance_id().is_ref_counted() {
                StaticRefCount::maybe_inc_ref(obj);
            }
        }

        fn maybe_dec_ref<T: GodotClass>(obj: &Gd<T>) -> bool {
            out!("  Dyn::dec   <{}>", std::any::type_name::<T>());
            if obj.instance_id().is_ref_counted() {
                StaticRefCount::maybe_dec_ref(obj)
            } else {
                false
            }
        }

        fn is_ref_counted<T: GodotClass>(obj: &Gd<T>) -> Option<bool> {
            // Return `None` if obj is dead
            obj.instance_id_or_none().map(|id| id.is_ref_counted())
        }
    }
```

Reproduction:

```rust
{
    let node = Node::new_alloc();
    let object = node.share().upcast::<Object>();
    node.free(); // or `queue_free`, etc.
}
// `object` dropped, `maybe_dec_ref` called, because the instance isn't valid `instance_id` fails
```

Which results  in `failed to call instance_id() on destroyed object; use instance_id_or_none() or keep your objects alive`.

### PR DESCRIPTION
**Pull request by WinstonHartnett**
Closes #172

### CODE REVIEW

**Comment by bluenote10** [comment]
FYI GitHub isn't smart enough to link to issues if they are only referenced in the PR title. If you put "closes #172" in the description it is linked and will auto-close once merged.

**Comment by Bromeon** [comment]
Thanks!

Could you add the original reproducing example as an `#[itest]` in object_test.rs?

**Review by Bromeon — COMMENTED** [review]
Thanks!

bors r+

**Comment by Bromeon** [comment]
Network errors...

bors r+

**Pull request merged**
