### PR TITLE
Run CI against stable Godot runtime

### PR DESCRIPTION
**Pull request by Bromeon**
Adds CI jobs that **run** against stable release of the last Godot minor version (here 4.0.3).

This distinction is important, as we have two dimensions of Godot versions now:
* **GDExtension API** -- this is the version of the GDExtension API against which gdext is _compiled_.
* **Runtime** -- this is the version of the Godot binary under which gdext _runs_.

By default, most jobs include latest Godot nightly version (so that is not explicitly annotated in the names).
`-nightly` means that a nightly _API_ version is used. `stableRt` means stable _runtime_ (the new jobs).

Includes #285 as a base, as that is required to fix failing jobs with Godot 4.0.3 stable.

Runs only clang memchecks for now; the gcc ones don't add that much, and we already have a huge number of jobs now. We may reduce this over time.

### CODE REVIEW

**Comment by Bromeon** [comment]
I had problems with a segfault in `windows-stable-4.0.3` before, let's see if this still occurs 🤔 

bors r+

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-288

**Comment by Bromeon** [comment]
One CI job `linux-memcheck-stable-4.0.3` is still failing with memory leaks. This one runs the current gdext version (compiled against 4.0.3 API) with a Godot 4.0.3 binary.

I haven't managed to isolate the leaks, as I cannot reproduce them locally (with Win10 + WSL2), and they don't seem to follow a 1:1 per-use pattern. For example, calling `Array::default()` causes a leak, but calling it twice doesn't cause _more_ leaks, despite the stack trace pointing to this allocation. I wonder if this is a systematic problem similar to the `dlclose` issue from #133.

To make matters worse, nightly.link is currently down too, meaning all our artifact-depending CI is not operational. If this persists, we need to migrate away from it by manually calling/searching several GitHub Actions REST APIs 😕 

bors try
(guaranteed failure)

**Comment by Bromeon** [comment]
Just now, https://nightly.link seems up again, at least the website. So let's try again...

bors try

**Pull request merged**
