### PR TITLE
More robust checks against "OpenXR*" classes on macOS

### LINKED ISSUE #474: build fails in macos due to `failed to resolve: could not find open_xr_action in engine`
I updated from 4.1.1 to 4.1.3, and gdext from `00ba8c9d` to `02f4acf5` and I started getting the following error in MacOS (Windows and Linux are OK):

```
error[E0433]: failed to resolve: could not find `open_xr_action` in `engine`
  --> /Users/mateomiccino/.cargo/git/checkouts/gdext-76630c89719e160c/02f4acf/godot-core/src/gen/classes/open_xr_interaction_profile_metadata.rs:88:223
   |
88 | ...dotString, action_type: crate::engine::open_xr_action::ActionType,) {
   |                                           ^^^^^^^^^^^^^^ could not find `open_xr_action` in `engine`

error[E0433]: failed to resolve: could not find `open_xr_action` in `engine`
  --> /Users/mateomiccino/.cargo/git/checkouts/gdext-76630c89719e160c/02f4acf/godot-core/src/gen/classes/open_xr_interaction_profile_metadata.rs:90:113
   |
90 |             type CallSig = ((), GodotString, GodotString, GodotString, GodotString, GodotString, crate::engine::open_xr_action::ActionType);
   |                                                                                                                 ^^^^^^^^^^^^^^ could not find `open_xr_action` in `engine`
```

I compared the generated files (at .cargo/git/checkouts/gdext-76630c89719e160c/02f4acf/godot-core/src/gen/classes) between Linux and Mac, and Mac is not generating the `open_xr_**` files, it just generating the `open_xr_interaction_profile_metadata`.

More details in a GH Action:
https://github.com/decentraland/godot-explorer/actions/runs/6824669204/job/18561040610

I'm using pre-build
```
[patch."https://github.com/godot-rust/godot4-prebuilt".godot4-prebuilt]
git = "https://github.com//godot-rust/godot4-prebuilt"
branch = "4.1.3"
```
entire cargo.toml: https://github.com/decentraland/godot-explorer/blob/main/rust/decentraland-godot-lib/Cargo.toml

### PR DESCRIPTION
**Pull request by Bromeon**
Closes #474.

### CODE REVIEW

**Review by kuruk-mm — APPROVED** [review]
Looks great. I tested it locally, and it fixes the problem.

**Comment by Bromeon** [comment]
@kuruk-mm Could you check if this fixes your issue?

Change Cargo.toml like this:
```toml
[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "bugfix/macos-openxr" }
```

**Comment by kuruk-mm** [comment]
> heck if this fixes your issue?

Yes, I confirm.

I added
```
[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "bugfix/macos-openxr" }

[patch."https://github.com/godot-rust/godot4-prebuilt".godot4-prebuilt]
git = "https://github.com//godot-rust/godot4-prebuilt"
branch = "4.1.3"
```

and it's working well, if I change branch = "master", it fails.

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-475

**Pull request merged**
