### PR TITLE
Fix `validate_unicode_scalar_sequence` build errors on aarch64

### PR DESCRIPTION
**Pull request by therealbnut**
Hey, I'm not sure if this is as performant as it was intended, but this at least allows me to compile on `aarch64`.

Before these changes I had these errors:
```
error[E0599]: no function or associated item named `load_unaligned` found for struct `std::arch::aarch64::uint32x4_t` in the current scope
  --> godot-core/src/builtin/string_chars.rs:58:37
   |
58 |             let block = uint32x4_t::load_unaligned(ptr as *const u32);
   |                                     ^^^^^^^^^^^^^^ function or associated item not found in `uint32x4_t`

error[E0425]: cannot find function `vqmovltq_u32` in this scope
    --> godot-core/src/builtin/string_chars.rs:61:17
     |
61   |             if (vqmovltq_u32(block, vdupq_n_u32(char::MAX as u32))).any() {
     |                 ^^^^^^^^^^^^ help: a function with a similar name exists: `vmovl_u32`
     |
    ::: stdarch/crates/core_arch/src/arm_shared/neon/mod.rs:3335:1
     |
3335 | pub unsafe fn vmovl_u32(a: uint32x2_t) -> uint64x2_t {
     | ---------------------------------------------------- similarly named function `vmovl_u32` defined here

error[E0599]: no method named `is_zero` found for struct `std::arch::aarch64::uint32x4_t` in the current scope
  --> godot-core/src/builtin/string_chars.rs:70:14
   |
66 |               if !vandq_u32(
   |  _________________-
67 | |                 vcgtq_u32(block, vdupq_n_u32(0xD7FF)),
68 | |                 vcltq_u32(block, vdupq_n_u32(0xE000)),
69 | |             )
70 | |             .is_zero()
   | |             -^^^^^^^ method not found in `uint32x4_t`
   | |_____________|
```

It now passes `./check.sh test`.

### CODE REVIEW

**Comment by Bromeon** [comment]
These are precisely the sort of portability issues I was afraid of in https://github.com/godot-rust/gdext/pull/161#pullrequestreview-1331559749 🙈

Thanks a lot for addressing this! 👍 
Could you remove the `// still untested but it should work` comment?

bors try

**Comment by Bromeon** [comment]
Thanks for the quick update! Could you squash the commits to 1?

I saw that `bors try` failed, but it seems like a spurious error related to network, so don't worry about it. I will re-run it.
https://github.com/godot-rust/gdext/actions/runs/4402554456/jobs/7709839953

bors retry

**Comment by Bromeon** [comment]
bors try-
bors try

**Comment by therealbnut** [comment]
> Thanks for the quick update! Could you squash the commits to 1?

No problem, done.

Btw - there's a Github project setting to [squash on merge by default](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests). This assumes that the project's workflow is to manually merge after CI.

**Comment by therealbnut** [comment]
> Yes, but that has other disadvantages, namely that CI is not tested against `master`.

Yeah, that's a problem - and if bors is doing merging for you that's probably the best solution.

Although FYI if you're not expecting a lot of PRs to merge in a short time you can also ["require status checks to be up to date"](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging). The downside of that is you may have to run CI, and then re-run it if someone else merges first, although if there's not a huge (>10) number of active contributors that isn't really an issue.

**Comment by therealbnut** [comment]
@Bromeon thanks for the review!

**Pull request merged**
