### PR TITLE
Fix `enum_test.rs` accidentally excluded from itest

### PR DESCRIPTION
**Pull request by 0x53A**
I randomly notice that the file enum_tests.rs was not included in the project, and therefore not compiled and tested.

image

If not including it was on purpose pls just close the PR

### CODE REVIEW

**Comment by Bromeon** [comment]
Good catch, that's definitely not intended. Thank you!

Could you eventually squash the commits to 1? Also, let me know if you need help with the CI that now fails 🙂

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-931

**Comment by 0x53A** [comment]
done(, i hope).

what's the command to run itest locally?

**Comment by Bromeon** [comment]
> what's the command to run itest locally?


`./check.sh itest`, see also [this page](https://godot-rust.github.io/book/contribute/dev-tools.html) in the book :slightly_smiling_face: 

Note that local testing is best-effort and not 100% the same as CI, so in case of discrepancies, consider CI the authority.

**Pull request merged**
