### PR TITLE
Implement `Display` trait for some built-in types

### PR DESCRIPTION
**Pull request by Hapenia-Lans**
related to #110 .

### CODE REVIEW

**Comment by Bromeon** [comment]
Thanks a lot!

Is this the Godot `str()` representation of these types?

Instead of separate tests and `//` comments inside the implementation, the string representation could be documented with `///` and be part of a Rust doctest. That way, the user would see how it looks and we would verify it. One example per type should already be enough.

Please also squash your commits as per [contribution guidelines](https://github.com/godot-rust/gdext/blob/master/Contributing.md). And if possible, avoid commit messages like containing `#` + a number, as GitHub interprets those as issue references and creates a lot of cross-referencing spam. Thank you 🙂

**Comment by Bromeon** [comment]
I assume the close was unintentional, since you pushed to the branch afterwards?

**Comment by Hapenia-Lans** [comment]
unable to squash these commits. maybe i should close this and create a new one?

**Comment by Hapenia-Lans** [comment]
Deprecated. Something goes wrong when I try to solve conflict with upstream updates. I will open a new pull request and redo changes.

**Comment by Bromeon** [comment]
In the future, please force-push the relevant changes to your branch:
```bash
git push --force-with-lease
# or if you don't care about discarding any upstream work:
git push --force
```

Not opening 2 PRs for the same thing helps keeping an overview. Thanks! 🙂 

Superseded by #224.

**Pull request closed without merging**
