### PR TITLE
Add `get` and `set` as virtual methods

### PR DESCRIPTION
**Pull request by lilizoey**

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-567

**Comment by Bromeon** [comment]
Thanks a lot! Is it OK if this waits until after my announced refactoring? I hope it doesn't cause too many conflicts 😕 but the other way around would be a nightmare...

**Comment by lilizoey** [comment]
> Thanks a lot! Is it OK if this waits until after my announced refactoring? I hope it doesn't cause too many conflicts 😕 but the other way around would be a nightmare...

Ye no worries

**Review by Bromeon — COMMENTED** [review]
Thanks! Interestingly, #573 did not break this 👀 

I'll merge this due to further refactorings causing lots of divergence, but I might change a few things in follow-up PRs.

**Pull request merged**
