### PR TITLE
Migrate crate-local `/gen` directories to `OUT_DIR`

### LINKED ISSUE #506: Jetbrains IDEs don't support static analysis of generated code in `OUT_DIR`
We can currently not generate sources inside `target` (via `OUT_DIR`), because CLion/RustRover do not recognize symbols in that directory, completely breaking user experience. This is however likely a blocker for #2 (unless we consider `#[cfg]` shenanigans).

Upstream: [RUST-12312](https://youtrack.jetbrains.com/issue/RUST-12312/Unsupported-cases-with-include-macros) on YouTrack. 
Please upvote if you can. It looks like a solution is already being worked on.

### PR DESCRIPTION
**Pull request by Bromeon**
Please help test this pull request on different IDEs. In the past, we experienced problems with static analysis and symbol completion when using `OUT_DIR`.

To try this PR, you can run `cargo clean`, then replace your `godot` entry in Cargo.toml with this:
```toml
[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "feature/output-dir" }
```

## Jetbrains

On Jetbrains IDEs, it may be necessary to run _Cargo refresh_:

Cargo refresh

## Feedback

I'd appreciate if you could then respond here quickly with your IDE, **its version** and if things work (out of the box, or if a manual step like _Cargo refresh_ is needed).

Closes #506.

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-687

**Comment by LeaoLuciano** [comment]
Seems fine on VSCode (for Linux) using Rust-Analyzer extension (v0.4.1943)

**Comment by fstxz** [comment]
VSCodium 1.87.2 on Linux (Flatpak version). Works out of the box.

**Comment by StatisMike** [comment]
Works on Linux, VSCode + RustAnalyzer. Also tested whole build process and godot export on CI in [`gd-rehearse`](https://github.com/StatisMike/gd-rehearse/actions/runs/8927408126).

**Comment by jacobsky** [comment]
Tested on VSCode (windows) with Rust Analyzer, and there were no issues.

**Comment by Bromeon** [comment]
Bringing this to `master` to expose it to more testing. If people run into issue, we can always rethink our approach.

**Pull request merged**
