### PR TITLE
Validate that virtual extension classes require `#[class(tool)]`

### PR DESCRIPTION
**Pull request by Bromeon**
Adds validation for an issue brought up in https://github.com/godot-rust/gdext/issues/826#issuecomment-2282202619.

@TitanNano you might want to have a look?

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-850

**Comment by TitanNano** [comment]
Looks good. Tried it with `ScriptExtension` and `ScriptLanguageExtension`.

**Comment by TitanNano** [comment]
@Bromeon I see I'm just a bit too late. It just came to my mind that we perhaps also want to include `EditorPlugin` here. There are also some import Plugin classes that are only used in the editor.

**Comment by Bromeon** [comment]
Hm good idea -- would you mind opening a PR for it? Since you already have some classes in mind :thinking: 
I think the structure could follow the changes from this PR quite closely.

**Comment by TitanNano** [comment]
Yeah I can do that.

**Pull request merged**
