### PR TITLE
`#[class(no_init)]` to explicitly disable constructor

### LINKED ISSUE #539: Classes without `init` break hot reloading
It seems like a single class that is declared as something like:
```rs
#[derive(GodotClass)]
#[class(base=Node2D)]
struct MyClass {}
```
-- that is, no `#[class(init)]` and no manual override of `fn init()` -- is enough to break hot reloading.

The Godot error message is not helpful:
> ERROR: Extension marked as reloadable, but attempted to register class 'MyClass' which doesn't support reloading. Perhaps your language binding don't support it? Reloading disabled for this extension.

---

There are several measures we can take:

1. Prioritize the already planned init-refactoring (it's also easy to forget; maybe something like `no_init` could work?)
2. Make sure that classes without `init` method are registered properly in GDExtension, meaning they are without a default constructor but otherwise functional.
    - Maybe the `recreate_fn` is needed.
3. If having a constructor is a hard requirement for hot reloading in GDExtension, we can either:
   - Enforce that all classes have one, if hot reloading is enabled (if we can detect `reloadable=true` at startup)
   - Supply a "dummy" one just for this case, although that might come with follow-up issues

Long-term, we could probably expose something like a `reinit()` constructor that is invoked on hot reloads, and by default calls `init`. But before working on more features, I'd like to get the base robust.

### PR DESCRIPTION
**Pull request by Bromeon**
Adds `#[class(no_init)]`, which is now **required** to disable constructor. 
This is a breaking change for cases where the constructor was implicitly disabled -- but this didn't work properly anyway, see below.

Forgetting a constructor is no longer possible: if there is no `#[class(init)]` attribute and no overridden `init()` function, then the library will emit a compile error. In many cases, constructors were accidentally disabled due to forgotten `#[class(init)]`, which also broke hot reloading.

In addition, the `no_init` key now registers a class properly as non-instantiable (in Godot terms "abstract", which is confusing). This means that you get a helpful error message in the editor in case you call `MyClass.new()` from GDScript:
```
ERROR: Class 'MyClass' or its base class cannot be instantiated.
```

Fixes #539.

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-593

**Comment by bluenote10** [comment]
> Forgetting a constructor is no longer possible: if there is no #[class(init)] attribute and no overridden init() function, then the library will emit a compile error. 

Is it actually by design that this compiler error is a little bit cryptic? Or is that rather an accidental regression?

For me the compiler would currently fail with something like:

```
error[E0277]: the trait bound `SomeClass: GodotDefault` is not satisfied
   --> src/lib.rs:190:12
    |
190 | pub struct SomeClass {
    |            ^^^^^ the trait `GodotDefault` is not implemented for `SomeClass`
    |
    = help: the following other types implement trait `GodotDefault`:
              TreeRoot
              ClassicCounter
              Counter
              AesContext
              AStar2D
              AStar3D
              AStarGrid2D
              AcceptDialog
            and 710 others
note: required by a bound in `class_SomeClass_must_have_an_init_method::__type_check`
   --> src/lib.rs:188:10
    |
188 | #[derive(GodotClass)]
    |          ^^^^^^^^^^ required by this bound in `__type_check`
    = note: this error originates in the derive macro `GodotClass` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I vaguely remembered seeing this PR, which is why I fortunately made the right guess that I had to add `no_init`. I'd imagine that without prior knowledge this error could be a bit misleading, because the intuitive solution would be to try implementing `GodotDefault` manually, i.e., the `no_init` switch is hard to discover.

**Comment by Bromeon** [comment]
On another note, I did add a [dedicated chapter about constructors](https://godot-rust.github.io/book/register/constructors.html) just yesterday, which also elaborates `#[class(no_init)]`.

That doesn't dismiss the importance of having good error messages, especially since this one can happen accidentally, but it provides additional knowledge.

**Comment by bluenote10** [comment]
Thanks for clarifying! I somehow guessed that at the time this was introduced the message was better, and it had degraded accidentally.

> Do you have a suggestion how to improve errors here?

The problem with "must have init" is that it may also be misleading, because it sounds like having an `init` in one way or another is always mandatory. I was hoping we can somehow create a custom error in the macro. But if that is not possible what about renaming `__type_check` to a more explicit `__class_without_init_must_be_marked_with_no_init`. This would at least give a hint that there are two options: either add an init or go for "no init". What "marking with no init" exactly means is of course hard to explain via a symbol.

> On another note, I did add a [dedicated chapter about constructors](https://godot-rust.github.io/book/register/constructors.html) just yesterday, which also elaborates #[class(no_init)].

We could also mention that error there, but it still may be hard for users to discover.

**Comment by Bromeon** [comment]
> I was hoping we can somehow create a custom error in the macro.

The error doesn't happen at macro evaluation time, but only when the expanded code is compiled.

It _is_ allowed to have neither `#[class(init)]` nor `#[class(no_init)]`, namely when a user-defined `init()` function is provided. This is however declared inside a `#[godot_api]` impl block, which is a _different_ macro from `#[derive(GodotClass)]`. The two don't know about each other.

This all sucks quite a bit, but unfortunately our hope at ever getting proper compile-time introspection (rather than these proc-macro hacks) was shattered by [very professional Rust leadership](https://thephd.dev/i-am-no-longer-speaking-at-rustconf-2023).

---

> But if that is not possible what about renaming `__type_check` to a more explicit `__class_without_init_must_be_marked_with_no_init`.

Something like this should be possible 👍 

---



> We could also mention that error there, but it still may be hard for users to discover.

There is already a [mention of this](https://godot-rust.github.io/book/register/constructors.html#disabled-init):

> Not providing/generating an `init` method and forgetting to use `#[class(no_init)]` will result in a compile-time error.

I'd rather not mention the concrete error wording -- it's one more thing that goes out of sync, and it's very unlikely that people find that page in the book when enountering the error.

**Comment by bluenote10** [comment]
> I'd rather not mention the concrete error wording -- it's one more thing that goes out of sync, and it's very unlikely that people find that page in the book when enountering the error.

For me it simply would have helped, because the error "the trait bound `SomeClass: GodotDefault` is not satisfied" sounded not at all like _that_ error message, but something completely different. A small info box a la 

>Note that the error manifest itself in the form of an unsatisfied trait bound like _the trait bound `SomeClass: GodotDefault` is not satisfied_.

would have clarified it for me. Perhaps it would also make the error googlable...

**Pull request merged**
