### PR TITLE
Virtual methods take `Option<Gd<T>>` (unless whitelisted)

### PR DESCRIPTION
**Pull request by Bromeon**
Fixes https://github.com/godot-rust/gdext/issues/494. There is [a list with exceptions](https://github.com/godot-rust/gdext/blob/3981f0463c3559242d844c5af05381bd9f408a0e/godot-codegen/src/special_cases/special_cases.rs#L275-L285).

> [!tip]
> **Please help me correct and complete this.**

If you encounter parameters that are provably non-null (through docs or implementation), please don't just `.unwrap()` them but maybe mention them in a comment here (even after PR is closed), or open a PR directly.

---

My mid-term hope is still that we can query this information from Godot itself. There are efforts like https://github.com/godotengine/godot/pull/86079 underway.

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-883

**Comment by andreymal** [comment]
yay it works

`EditorPlugin._handles(objects)` seems to be non-null btw

<a href="https://github.com/user-attachments/assets/7fbd7dcf-eb38-4a3f-a5ac-ba05e358d378" target="_blank"></a>

**Comment by Bromeon** [comment]
Merging now. I'd appreciate input about more parameters that can be non-null in this thread. 

On [Discord](https://discord.com/channels/723850269347283004/1280521317568745482), it was stated that we should use non-null by default and special-case the parameters that _are_ null, because those are typically documented. However, a single mistake here would mean the API is unusable and needs a breaking SemVer change (`Gd<T>` -> `Option<Gd<T>>`), whereas a mistake this way just comes at a slight inconvenience (extra `.unwrap()`).

**Comment by lmsonic** [comment]
Hi, I scoured the API for documentation for when virtual methods mention null in their description. This is not exhaustive because there are a bunch of <CLASS_NAME>Extension classes not documented that have virtual methods that correspond to methods in the default godot classes that might pass null values.

# Control
- **[Object](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object)\_make_custom_tooltip(for_text: [String](https://docs.godotengine.org/en/4.3/classes/class_string.html#class-string)) virtual const**

Virtual method to be implemented by the user. Returns a **Control** node that should be used as a tooltip instead of the default one. The `for_text` includes the contents of the [tooltip_text](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-property-tooltip-text) property.

The returned node must be of type **Control** or Control-derived. It can have child nodes of any type. It is freed when the tooltip disappears, so make sure you always provide a new instance (if you want to use a pre-existing node from your scene tree, you can duplicate it and pass the duplicated instance). When `null` or a non-Control node is returned, the default tooltip will be used instead.

The returned node will be added as child to a [PopupPanel](https://docs.godotengine.org/en/4.3/classes/class_popuppanel.html#class-popuppanel), so you should only provide the contents of that panel. That [PopupPanel](https://docs.godotengine.org/en/4.3/classes/class_popuppanel.html#class-popuppanel) can be themed using [Theme.set_stylebox](https://docs.godotengine.org/en/4.3/classes/class_theme.html#class-theme-method-set-stylebox) for the type `"TooltipPanel"` (see [tooltip_text](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-property-tooltip-text) for an example).

**Note:** The tooltip is shrunk to minimal size. If you want to ensure it's fully visible, you might want to set its [custom_minimum_size](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-property-custom-minimum-size) to some non-zero value.

**Note:** The node (and any relevant children) should be [CanvasItem.visible](https://docs.godotengine.org/en/4.3/classes/class_canvasitem.html#class-canvasitem-property-visible) when returned, otherwise, the viewport that instantiates it will not be able to calculate its minimum size reliably.

**Example of usage with a custom-constructed node:**

```gdscript
func _make_custom_tooltip(for_text):
	var label = Label.new()
	label.text = for_text
	return label
```

**Example of usage with a custom scene instance:**

```gdscript
func _make_custom_tooltip(for_text):
	var tooltip = preload("res://some_tooltip_scene.tscn").instantiate()
	tooltip.get_node("Label").text = for_text
	return tooltip
```
- **[Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant) \_get_drag_data (at_position: [Vector2](https://docs.godotengine.org/en/4.3/classes/class_vector2.html#class-vector2)) virtual**

Godot calls this method to get data that can be dragged and dropped onto controls that expect drop data. Returns `null` if there is no data to drag. Controls that want to receive drop data should implement [can_drop_data](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-private-method-can-drop-data) and [drop_data](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-private-method-drop-data). `at_position` is local to this control. Drag may be forced with [force_drag](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-method-force-drag).

A preview that will follow the mouse that should represent the data can be set with [set_drag_preview](https://docs.godotengine.org/en/4.3/classes/class_control.html#class-control-method-set-drag-preview). A good time to set the preview is in this method.

```gdscript
func _get_drag_data(position):
	var mydata = make_data() # This is your custom method generating the drag data.
	set_drag_preview(make_preview(mydata)) # This is your custom method generating the preview of the drag data.
	return mydata
```

# EditorPlugin
- **void \_edit(object: [Object](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object)) virtual[](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-private-method-edit)**

This function is used for plugins that edit specific object types (nodes or resources). It requests the editor to edit the given object.

`object` can be `null` if the plugin was editing an object, but there is no longer any selected object handled by this plugin. It can be used to cleanup editing state.

# EditorScenePostImport

Post-processes scenes after import.

## Description

Imported scenes can be automatically modified right after import by setting their **Custom Script** Import property to a `tool` script that inherits from this class.

The [post_import](https://docs.godotengine.org/en/4.3/classes/class_editorscenepostimport.html#class-editorscenepostimport-private-method-post-import) callback receives the imported scene's root node and returns the modified version of the scene. Usage example:
```gdscript
@tool # Needed so it runs in editor.
extends EditorScenePostImport

# This sample changes all node names.
# Called right after the scene is imported and gets the root node.
func _post_import(scene):
	# Change all node names to "modified_[oldnodename]"
	iterate(scene)
	return scene # Remember to return the imported scene

func iterate(node):
	if node != null:
		node.name = "modified_" + node.name
		for child in node.get_children():
			iterate(child)
```

**[Object](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object) \_post_import(scene: [Node](https://docs.godotengine.org/en/4.3/classes/class_node.html#class-node)) virtual[](https://docs.godotengine.org/en/4.3/classes/class_editorscenepostimport.html#class-editorscenepostimport-private-method-post-import)**

Called after the scene was imported. This method must return the modified version of the scene.

# EditorScenePostImportPlugin

[Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant) **\_get_option_visibility**(path: [String](https://docs.godotengine.org/en/4.3/classes/class_string.html#class-string), for_animation: [bool](https://docs.godotengine.org/en/4.3/classes/class_bool.html#class-bool), option: [String](https://docs.godotengine.org/en/4.3/classes/class_string.html#class-string)) virtual const[](https://docs.godotengine.org/en/4.3/classes/class_editorscenepostimportplugin.html#class-editorscenepostimportplugin-private-method-get-option-visibility)

Return true or false whether a given option should be visible. Return null to ignore.

[Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant) **\_get_option_visibility**(path: [String](https://docs.godotengine.org/en/4.3/classes/class_string.html#class-string), for_animation: [bool](https://docs.godotengine.org/en/4.3/classes/class_bool.html#class-bool), option: [String](https://docs.godotengine.org/en/4.3/classes/class_string.html#class-string)) virtual const[](https://docs.godotengine.org/en/4.3/classes/class_editorscenepostimportplugin.html#class-editorscenepostimportplugin-private-method-get-option-visibility)

Return true or false whether a given option should be visible. Return null to ignore.
# GLTFDocumentExtension

[Error](https://docs.godotengine.org/en/4.3/classes/class_%40globalscope.html#enum-globalscope-error) **\_export_node**(state: [GLTFState](https://docs.godotengine.org/en/4.3/classes/class_gltfstate.html#class-gltfstate), gltf_node: [GLTFNode](https://docs.godotengine.org/en/4.3/classes/class_gltfnode.html#class-gltfnode), json: [Dictionary](https://docs.godotengine.org/en/4.3/classes/class_dictionary.html#class-dictionary), node: [Node](https://docs.godotengine.org/en/4.3/classes/class_node.html#class-node)) virtual[](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-export-node)

Part of the export process. This method is run after [_get_saveable_image_formats](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-get-saveable-image-formats) and before [_export_post](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-export-post). If this **GLTFDocumentExtension** is used for exporting images, this runs after [_serialize_texture_json](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-serialize-texture-json).

This method can be used to modify the final JSON of each node. Data should be primarily stored in `gltf_node` prior to serializing the JSON, but the original Godot `node` is also provided if available. The node may be null if not available, such as when exporting GLTF data not generated from a Godot scene.

[Node3D](https://docs.godotengine.org/en/4.3/classes/class_node3d.html#class-node3d) **\_generate_scene_node**(state: [GLTFState](https://docs.godotengine.org/en/4.3/classes/class_gltfstate.html#class-gltfstate), gltf_node: [GLTFNode](https://docs.godotengine.org/en/4.3/classes/class_gltfnode.html#class-gltfnode), scene_parent: [Node](https://docs.godotengine.org/en/4.3/classes/class_node.html#class-node)) virtual[](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-generate-scene-node)

Part of the import process. This method is run after [_import_post_parse](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-import-post-parse) and before [_import_node](https://docs.godotengine.org/en/4.3/classes/class_gltfdocumentextension.html#class-gltfdocumentextension-private-method-import-node).

Runs when generating a Godot scene node from a GLTFNode. The returned node will be added to the scene tree. Multiple nodes can be generated in this step if they are added as a child of the returned node.

**Note:** The `scene_parent` parameter may be null if this is the single root node.

# MultiplayerAPI \ 

[Error](https://docs.godotengine.org/en/4.3/classes/class_%40globalscope.html#enum-globalscope-error) **object_configuration_add**(object: [Object](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object), configuration: [Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant))[](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapi.html#class-multiplayerapi-method-object-configuration-add)

Notifies the MultiplayerAPI of a new `configuration` for the given `object`. This method is used internally by [SceneTree](https://docs.godotengine.org/en/4.3/classes/class_scenetree.html#class-scenetree) to configure the root path for this MultiplayerAPI (passing `null` and a valid [NodePath](https://docs.godotengine.org/en/4.3/classes/class_nodepath.html#class-nodepath) as `configuration`). This method can be further used by MultiplayerAPI implementations to provide additional features, refer to specific implementation (e.g. [SceneMultiplayer](https://docs.godotengine.org/en/4.3/classes/class_scenemultiplayer.html#class-scenemultiplayer)) for details on how they use it.

**Note:** This method is mostly relevant when extending or overriding the MultiplayerAPI behavior via [MultiplayerAPIExtension](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapiextension.html#class-multiplayerapiextension).

[Error](https://docs.godotengine.org/en/4.3/classes/class_%40globalscope.html#enum-globalscope-error) **object_configuration_remove**(object: [Object](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object), configuration: [Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant))[](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapi.html#class-multiplayerapi-method-object-configuration-remove)

Notifies the MultiplayerAPI to remove a `configuration` for the given `object`. This method is used internally by [SceneTree](https://docs.godotengine.org/en/4.3/classes/class_scenetree.html#class-scenetree) to configure the root path for this MultiplayerAPI (passing `null` and an empty [NodePath](https://docs.godotengine.org/en/4.3/classes/class_nodepath.html#class-nodepath) as `configuration`). This method can be further used by MultiplayerAPI implementations to provide additional features, refer to specific implementation (e.g. [SceneMultiplayer](https://docs.godotengine.org/en/4.3/classes/class_scenemultiplayer.html#class-scenemultiplayer)) for details on how they use it.

**Note:** This method is mostly relevant when extending or overriding the MultiplayerAPI behavior via [MultiplayerAPIExtension](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapiextension.html#class-multiplayerapiextension).

# MultiplayerAPIExtension

[Error](https://docs.godotengine.org/en/4.3/classes/class_%40globalscope.html#enum-globalscope-error) **\_object_configuration_add**(object: [Object](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object), configuration: [Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant)) virtual[](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapiextension.html#class-multiplayerapiextension-private-method-object-configuration-add)

Callback for [MultiplayerAPI.object_configuration_add](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapi.html#class-multiplayerapi-method-object-configuration-add).

[Error](https://docs.godotengine.org/en/4.3/classes/class_%40globalscope.html#enum-globalscope-error) **\_object_configuration_remove**(object: [Object](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object), configuration: [Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant)) virtual[](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapiextension.html#class-multiplayerapiextension-private-method-object-configuration-remove)

Callback for [MultiplayerAPI.object_configuration_remove](https://docs.godotengine.org/en/4.3/classes/class_multiplayerapi.html#class-multiplayerapi-method-object-configuration-remove).

# Object

[Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant) **\_get**(property: [StringName](https://docs.godotengine.org/en/4.3/classes/class_stringname.html#class-stringname)) virtual[](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object-private-method-get)

Override this method to customize the behavior of [get](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object-method-get). Should return the given `property`'s value, or `null` if the `property` should be handled normally.

Combined with [\_set](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object-private-method-set) and [\_get_property_list](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object-private-method-get-property-list), this method allows defining custom properties, which is particularly useful for editor plugins. Note that a property must be present in [get_property_list](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object-method-get-property-list), otherwise this method will not be called.
```gdscript
func _get(property):
	if property == "fake_property":
		print("Getting my property!")
		return 4

func _get_property_list():
	return [
		{ "name": "fake_property", "type": TYPE_INT }
	]
```

# OpenXRExtensionWrapperExtension

[Dictionary](https://docs.godotengine.org/en/4.3/classes/class_dictionary.html#class-dictionary) **\_get_requested_extensions**() virtual[](https://docs.godotengine.org/en/4.3/classes/class_openxrextensionwrapperextension.html#class-openxrextensionwrapperextension-private-method-get-requested-extensions)

Returns a [Dictionary](https://docs.godotengine.org/en/4.3/classes/class_dictionary.html#class-dictionary) of OpenXR extensions related to this extension. The [Dictionary](https://docs.godotengine.org/en/4.3/classes/class_dictionary.html#class-dictionary) should contain the name of the extension, mapped to a `bool *` cast to an integer:

- If the `bool *` is a `nullptr` this extension is mandatory.
    
- If the `bool *` points to a boolean, the boolean will be updated to `true` if the extension is enabled.

# ScriptExtension

[Variant](https://docs.godotengine.org/en/4.3/classes/class_variant.html#class-variant) **\_get_script_method_argument_count**(method: [StringName](https://docs.godotengine.org/en/4.3/classes/class_stringname.html#class-stringname)) virtual const [🔗](https://docs.godotengine.org/en/4.3/classes/class_scriptextension.html#class-scriptextension-private-method-get-script-method-argument-count)

Return the expected argument count for the given `method`, or `null` if it can't be determined (which will then fall back to the default behavior).

**Comment by lmsonic** [comment]
Also, most of the time the Godot API mentions null, it's either a case of Default values to null, which are covered by the extension methods + [AsObjectArg](https://godot-rust.github.io/docs/gdext/master/godot/obj/trait.AsObjectArg.html#), or you can pass null to a non default argument (usually to "reset" things) which is covered by [AsObjectArg](https://godot-rust.github.io/docs/gdext/master/godot/obj/trait.AsObjectArg.html#), or some methods return null, which is represented in gdext by Option<Gd<CLASS_NAME>>. As mentioned at the top of my comment, sometimes it is mentions when some Variant in input or output can be null.

**Pull request merged**
