### PR TITLE
derive Clone, PartialEq, Debug for native structs

### LINKED ISSUE #404: Would it be possible to make `AudioFrame: Clone + Copy`?
Currently, the code generation seems to generate `AudioFrame` as

```rust
#[repr(C)]
pub struct AudioFrame {
    pub left: f32, pub right: f32,
}
```

Would it be possible the `derive(Clone, Copy)` here, perhaps also `PartialEq`? This would make a few things easier, and typically for a pair of floats implementing `Copy` should be fine. Or is there a reason why this must not be done?

### PR DESCRIPTION
**Pull request by vortexofdoom**
Ignore branch name. Closes #404

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-587

**Review by Bromeon — COMMENTED** [review]
Thanks for your contribution! 🙂 

Could you maybe add 3 `#[itest]` functions in [native_structures_test.rs](https://github.com/godot-rust/gdext/blob/master/itest/rust/src/engine_tests/native_structures_test.rs)? One for each trait.

Each test could use a different native structure (but one per test is enough).

**Comment by vortexofdoom** [comment]
Added! Included `ObjectId` for debug since it was simplest to write out manually, otherwise used existing constructors.

**Comment by Bromeon** [comment]
Last feedback round:
- run rustfmt
- end comments with full stop (`.`) when possible
- combine the 2 commits to a single one (following [Contributing.md](https://github.com/godot-rust/gdext/blob/master/Contributing.md))

Thanks! 🙂

**Comment by Bromeon** [comment]
To combine commits to one, a simple approach is:
```
git reset --soft master
git commit -am "message"
git push --force-with-lease
```

Make sure you keep the `--soft`!

**Comment by vortexofdoom** [comment]
Thanks! I kept missing steps.

**Comment by vortexofdoom** [comment]
Goofed

**Comment by Bromeon** [comment]
Thanks a lot for your first PR! 😊

**Pull request merged**
