### PR TITLE
fix `#[var]` docs typo

### PR DESCRIPTION
**Pull request by Lamby777**
This part confused me while CTRL+F-ing through the docs.

Relevant thread: https://discord.com/channels/723850269347283004/1231202121630748762

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-668

**Comment by Bromeon** [comment]
Thanks!

If you're already improving docs, could you change two more things?
(bold highlights changes, not formatting)

---

> Unlike C++, Rust doesn’t really have inheritance, but the GDExtension API lets us “inherit” from a built-in engine class.

"built-in engine" -> "Godot-provided engine"
base
---

> By default, classes created with this library inherit from RefCounted.

At the end, please write "inherit from RefCounted, like GDScript".

---

> If you dont also include

Should be "don't"


--- 

> because we have added a hide key to the class.

Should be "`hidden` key"

**Comment by Lamby777** [comment]
Sure, 1 sec.

**Comment by Lamby777** [comment]
i replaced all the other instances of `dont` in the last commit too, just in case (not including identifiers n stuff) :3

**Comment by Bromeon** [comment]
Thanks a lot! Could you combine the commits to a single one? 🙂

**Comment by Lamby777** [comment]
force pushed :3

**Comment by Bromeon** [comment]
Thank you! :slightly_smiling_face:

**Pull request merged**
