### PR TITLE
Revert "Merge pull request #581 from lilizoey/fix/static-mut-safety"

### PR DESCRIPTION
**Pull request by TCROC**
This reverts commit b4a91a6dcd150d36ef09f54acec8f96a913a136e, reversing changes made to 6243fc6c445df3f113f4203f650f2c6e15cf277a.

Hot reloads appear to have been broken by this PR.  Putting in a revert to get hot reloading back up and running while the cause is investigated.

### CODE REVIEW

**Comment by TCROC** [comment]
Not really sure why CI is unhappy here.

**Comment by kang-sw** [comment]
It seems this PR incurs compile error on `godot-core\src\private.rs:45:26` which utilizes new API introduced the commit being reverted by this one. 

```
    global_config.tool_only_in_editor //.
        && global_config.is_editor_or_init(is_editor)
        //               ^^^ This one
```

Removing that line compilation itself succeeds. (Of course idk if it works or not ..)

**Comment by TCROC** [comment]
Thanks for the heads up! I'll try it in the morning and see if it fixes it

**Comment by Bromeon** [comment]
I can't just revert all those changes to fix one issue. They improve on several other things, like thread safety.

We should isolate what causes the issue and fix that specifically.

**Review by Bromeon — CHANGES_REQUESTED** [review]
I can't just revert all those changes to fix one issue. They improve on several other things, like thread safety.

We should isolate what causes the issue and fix that specifically.

In this case, IIRC the assumption that some global initialization would only be called once was violated -- it's called multiple timed in hot reloading, which panics? If so, we should hook the hot reload notification to a flag, which is then considered on reload.

**Comment by StatisMike** [comment]
Full agreement with @Bromeon. @TCROC: Does enabling the `experimental-threads` feature fixes your issue ATM, as it does in #610 and #597?

If it does, we should maybe communicate better their (at least temporary) connection, and it should be used until we pinpoint the underlying issue at hand.

**Comment by TCROC** [comment]
@StatisMike This does indeed fix it! :)  I prefer this as a workaround rather than a revert.  I'll close this PR and open an issue to track it instead with a summary of our findings.

**Comment by Bromeon** [comment]
@TCROC this is already tracked in #629, please don't open a new one.

**Comment by TCROC** [comment]
Sounds good.  I won't :)

**Comment by Bromeon** [comment]
Fixed in https://github.com/godot-rust/gdext/pull/653.

**Pull request closed without merging**
